services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./db_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_REGISTRY_NAME}/${PROJECT_NAME}-backend:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    ports:
      - "3000:5000"